//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContract
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ModemServiceId { get; set; }
        public Nullable<int> ContarctId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual ModemService ModemService { get; set; }
    }
}
