//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModemService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModemService()
        {
            this.ClientContract = new HashSet<ClientContract>();
        }
    
        public int Id { get; set; }
        public int ModemId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime DateChanged { get; set; }
        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientContract> ClientContract { get; set; }
        public virtual Modem Modem { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
    }
}
